### ISSUE TITLE
What's the intuition behind encoding and then decoding the prompt?

### ISSUE THREAD

**Issue by Etelis** [lucataco/cog-phi-3-mini-4k-instruct#1]
Hey!
Thanks for the quick upload :)

I was wondering what was your intuition behind doing: 
`formatted_prompt = self.tokenizer.decode(self.tokenizer(chat_format)["input_ids"])`
It seems redundant 

Thanks!

**Comment by lucataco** [comment]
Yup, it was. I removed the line, thanks for the find!
